"""Generates lib/app/theme.dart: the app's light and dark "Ink" color schemes.

Material 3's 2021 color spec (the one Flutter's ColorScheme.fromSeed uses) is
applied to palettes of our own: the icon's ink as the primary color, kept at
its own tone (fidelity), and near-neutral surfaces, warm paper in the light
theme and graphite with a hint of ink in the dark one.
"""

import os

from materialyoucolor.dynamiccolor.dynamic_scheme import DynamicScheme
from materialyoucolor.dynamiccolor.material_dynamic_colors import MaterialDynamicColors
from materialyoucolor.dynamiccolor.variant import Variant
from materialyoucolor.hct.hct import Hct
from materialyoucolor.palettes.tonal_palette import TonalPalette

INK = 0xFF1B2638  # The dark leaf of the launcher icon.

# Neutral palettes as (hue, chroma). The icon's own paper color #F7F6F1 sits at
# hue 142 and would tint the light surfaces green, so the light theme uses a
# warmer hue; the dark theme takes the ink's hue.
LIGHT_NEUTRAL = (80.0, 2.0)
LIGHT_NEUTRAL_VARIANT = (80.0, 4.0)
DARK_NEUTRAL = (None, 4.0)
DARK_NEUTRAL_VARIANT = (None, 6.0)

# ColorScheme fields in constructor order, with the Material Color Utilities
# name where it differs.
FIELDS = [
    "primary", "onPrimary", "primaryContainer", "onPrimaryContainer",
    "primaryFixed", "primaryFixedDim", "onPrimaryFixed", "onPrimaryFixedVariant",
    "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
    "secondaryFixed", "secondaryFixedDim", "onSecondaryFixed", "onSecondaryFixedVariant",
    "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
    "tertiaryFixed", "tertiaryFixedDim", "onTertiaryFixed", "onTertiaryFixedVariant",
    "error", "onError", "errorContainer", "onErrorContainer",
    "surface", "onSurface", "surfaceDim", "surfaceBright",
    "surfaceContainerLowest", "surfaceContainerLow", "surfaceContainer",
    "surfaceContainerHigh", "surfaceContainerHighest", "onSurfaceVariant",
    "outline", "outlineVariant", "shadow", "scrim",
    "inverseSurface", "onInverseSurface", "inversePrimary", "surfaceTint",
]
RENAMED = {"onInverseSurface": "inverseOnSurface"}

# Fidelity picks text on containers at the lowest contrast it allows, which
# made a selected segment's label fainter than unselected ones. Text on
# containers takes tone 10 or 90 of its palette instead, as in Material 3's
# standard schemes, whichever is farther from the container.
ON_CONTAINERS = {
    "onPrimaryContainer": ("primaryContainer", "primary_palette"),
    "onSecondaryContainer": ("secondaryContainer", "secondary_palette"),
    "onTertiaryContainer": ("tertiaryContainer", "tertiary_palette"),
    "onErrorContainer": ("errorContainer", "error_palette"),
}

OUT = os.path.join(os.path.dirname(__file__), "..", "..", "lib", "app", "theme.dart")


def scheme(dark):
    ink = Hct.from_int(INK)
    hue = ink.hue
    chroma = max(ink.chroma, 16.0)
    nh, nc = DARK_NEUTRAL if dark else LIGHT_NEUTRAL
    vh, vc = DARK_NEUTRAL_VARIANT if dark else LIGHT_NEUTRAL_VARIANT
    return DynamicScheme(
        source_color_hct=ink,
        variant=Variant.FIDELITY,
        contrast_level=0.0,
        is_dark=dark,
        spec_version="2021",
        primary_palette=TonalPalette.from_hue_and_chroma(hue, chroma),
        secondary_palette=TonalPalette.from_hue_and_chroma(hue, min(chroma / 3, 10.0)),
        tertiary_palette=TonalPalette.from_hue_and_chroma((hue + 60) % 360, 24.0),
        neutral_palette=TonalPalette.from_hue_and_chroma(hue if nh is None else nh, nc),
        neutral_variant_palette=TonalPalette.from_hue_and_chroma(hue if vh is None else vh, vc),
        error_palette=TonalPalette.from_hue_and_chroma(25.0, 84.0),
    )


def constant(name, doc, dark):
    colors = MaterialDynamicColors(spec="2021")
    s = scheme(dark)
    lines = [f"/// {doc}", f"const {name} = ColorScheme(",
             f"  brightness: Brightness.{'dark' if dark else 'light'},"]
    for field in FIELDS:
        argb = getattr(colors, RENAMED.get(field, field)).get_argb(s)
        if field in ON_CONTAINERS:
            container, palette = ON_CONTAINERS[field]
            tone = Hct.from_int(getattr(colors, container).get_argb(s)).tone
            argb = getattr(s, palette).tone(10 if tone >= 50 else 90)
        lines.append(f"  {field}: Color(0x{argb & 0xFFFFFFFF:08X}),")
    lines.append(");")
    return "\n".join(lines)


def main():
    parts = [
        "// Generated by design/theme/gen.py. Do not edit by hand: change the",
        "// palettes there and run it again.",
        "",
        "import 'package:flutter/material.dart';",
        "",
        constant("inkLight", "The light theme: warm paper surfaces and an ink accent.", False),
        "",
        constant("inkDark", "The dark theme: graphite surfaces and a light steel accent.", True),
        "",
    ]
    with open(os.path.normpath(OUT), "w") as f:
        f.write("\n".join(parts))


if __name__ == "__main__":
    main()
